backend = "glx";

vsync = true;

unredir-if-possible = true;

shadow = false;
fading = false;
corner-radius = 0;
blur-background = false;
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

focus-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 1.0; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; }
  dropdown_menu = { opacity = 1.0; }
};
