separator=false
separator_block_width=2
markup=pango

[time]
command=date '+%a %d %b %H:%M:%S'
interval=1

[separator]
full_text=" | "

[volume]
command=~/.config/i3/scripts/volume.sh
interval=once
signal=1

[separator]
full_text=" | "

[battery]
command=~/.config/i3/scripts/bat.sh
interval=5

[separator]
full_text=" | "

[wifi]
command=~/.config/i3/scripts/wifi.sh
click=nm-connection-editor
interval=5
