unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded!"

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"

set -g status-position bottom

set -g mouse on
set -g renumber-windows on

set -g base-index 1
set -g pane-base-index 1

set -g status-justify absolute-centre
set -g status-left-length 100
set -g status-right-length 100

# set -g history-limit 50000

set -s escape-time 10

# Colors
set-option -g status-style "fg=#c0caf5,bg=#1a1b26"

setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
setw -g window-status-style "fg=#565f89,bg=#1a1b26"
setw -g window-status-current-style "fg=#c0caf5,bg=#3b4261,bold"

set -g status-left "#[fg=#1a1b26,bg=#7aa2f7,bold] #S "
set -g status-right "#[fg=#565f89,bg=#1a1b26] %Y-%m-%d #[fg=#1a1b26,bg=#7aa2f7,bold] %H:%M "

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"


# Window management (Alt + Shift Key)
bind -n M-N new-window -c "#{pane_current_path}" 
bind -n M-X kill-window
bind -n M-L next-window
bind -n M-H previous-window

# Pane navigation (Alt + hjkl)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Split panes using | and - 
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
